webtalk_init -webtalk_dir U:/cpre488/Labs/MP-1/ip_repo/edit_axi_ppm_v1_0.sim/sim_1/behav/xsim/xsim.dir/testbench_generate_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 18 12:04:21 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174156856_174156857_210694690_929" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c9e50d56-9052-4b90-a736-af8c50bdf920" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "dbd35b364c0b4e95af3f95fa9413cd59" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "46" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1240 v6 @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "25 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7736_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3824118799 -regid "174156856_174156857_210694690_929" -xml U:/cpre488/Labs/MP-1/ip_repo/edit_axi_ppm_v1_0.sim/sim_1/behav/xsim/xsim.dir/testbench_generate_behav/webtalk/usage_statistics_ext_xsim.xml -html U:/cpre488/Labs/MP-1/ip_repo/edit_axi_ppm_v1_0.sim/sim_1/behav/xsim/xsim.dir/testbench_generate_behav/webtalk/usage_statistics_ext_xsim.html -wdm U:/cpre488/Labs/MP-1/ip_repo/edit_axi_ppm_v1_0.sim/sim_1/behav/xsim/xsim.dir/testbench_generate_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
